# PocketFurnace Configuration File
# Prices to smelt, burn or cook one unit of the particular item:
cobblestone: 1
clay_ball: 1
gold_ore: 1
iron_ore: 1
sand: 1
pork: 1
raw_beef: 1
raw_chicken: 1
raw_fish: 1
log: 1